### ISSUE TITLE
cp -R Breaks the Windows Build

### ISSUE THREAD

**Issue by celtic-coder** [breck7/pldb#156]
Hi Breck (@breck7),

I've been experimenting today with the PLDB build on Windows. Since the build is Linux based, I had to put some workarounds in place to get the steps to work on my machine. They were as follows:

`npm install .`
`cd code`
`C:\pldb\node_modules\.bin\tsc.ps1`
`node .\SiteBuilder.js buildAll`

Note: I ignored the *chmod* commands in the **tsc** step as they do not apply on Windows. 

[package.json: lines 18 and 19](https://github.com/breck7/pldb/blob/main/package.json#L18-L19)

![tsc-and-plusx-scripts](https://user-images.githubusercontent.com/11787866/193357648-d83d452f-2f20-49be-bf4a-8d6fd9da3b96.png)

This is also true in the **build** step:

[package.json: line 5](https://github.com/breck7/pldb/blob/main/package.json#L5)

![build-step](https://user-images.githubusercontent.com/11787866/193358398-ec046563-0846-49af-99cb-342b3b7b1583.png)

It is at this point in the process that the error occurs:

![cp-R-error-in-build](https://user-images.githubusercontent.com/11787866/193356957-5c8fe255-ee04-48e1-a32d-6bcc34c731a7.png)

As can be seen, the **cp** command is invalid here. In Windows, one might use the **xcopy** command to recursively copy files and folders. 

Since there might be a requirement to have platform specific commands for this portion of the build process, might it be necessary to have  separate instructions at this point? Or is there another way of completing the build that will apply to both platforms?

Kind Regards,
Liam

**Comment by breck7** [comment]
Let me look at refactoring the build. I'm not happy with its current implementation (pretty slow)

**Comment by martin12333** [comment]
(BTW, git-for-windows, and WSL, do have  `cp -R`)

**Comment by celtic-coder** [comment]
Hi Martin (@martin12333),

Thanks for letting me know! That is very useful. I'll give it a try when I have time and see how it goes.

Kind Regards,
Liam

**Comment by breck7** [comment]
Hey @celtic-coder,

Any chance you have a Windows machine you could test whether PLDB builds on windows now? It is now just built on Scroll, so the tech stack is a lot simpler, and maybe it will work now.

```
 git clone https://github.com/breck7/pldb
 cd pldb
 # Required to run this during first install only.
 npm i -g cloc
 # Required to run this on fresh checkout and when upgrading from an old checkout or periodically when there are new releases
 npm install .
 # (Optional) Run tests
 npm run test
 npm run build
```

**Comment by celtic-coder** [comment]
Hi Breck (@breck7),

I would like to work on this, but I'm going away on vacation for about a week or so, starting Wednesday. I'll try to get to this possibly tomorrow. Otherwise, it may have to wait for my return.

Kind Regards,
Liam

**Comment by celtic-coder** [comment]
Hi Breck (@breck7),

My repo is installed at `c:\pldb` and my outputs were as follows:

<details><summary>npm i -g cloc</summary>
<p>

~~~
added 1 package in 49s
npm notice
npm notice New minor version of npm available! 10.0.0 -> 10.8.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.0
npm notice Run npm install -g npm@10.8.0 to update!
npm notice
~~~

</p>
</details>

This is the usually expected output. I upgraded to 10.8.0 and then proceeded to the next step.

<details><summary>npm install .</summary>
<p>

~~~
npm warn deprecated superagent@8.1.2: Please upgrade to v9.0.0+ as we have fixed a public vulnerability with formidable dependency. Note that v9.0.0+ requires Node.js v14.18.0+. See https://github.com/ladjs/superagent/pull/1800 for insight. This project is supported and maintained by the team at Forward Email @ https://forwardemail.net

added 102 packages, and audited 103 packages in 2m
~~~
</p>
</details>

There was a message about upgrading *superagent*, but otherwise it was fine. However, I encountered a problem running the test.

<details><summary>npm run test</summary>
<p>

~~~
> pldb@10.0.0 test
> scroll list | scroll test

Error in compiled grammar code for language "scroll"
node:internal/modules/cjs/loader:1227
  throw err;
  ^

Error: Cannot find module 'C:pldb
ode_modulesscroll-cli
ode_modulesjtreeproducts/Utils.js'
Require stack:
- C:\pldb\node_modules\scroll-cli\node_modules\jtree\products\GrammarLanguage.js
- C:\pldb\node_modules\scroll-cli\node_modules\jtree\products\TreeFileSystem.js
- C:\pldb\node_modules\scroll-cli\scroll.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1224:15)
    at Module._load (node:internal/modules/cjs/loader:1050:27)
    at Module.require (node:internal/modules/cjs/loader:1310:19)
    at require (node:internal/modules/helpers:179:18)
    at evalmachine.<anonymous>:2:19
    at Script.runInThisContext (node:vm:136:12)
    at Object.runInThisContext (node:vm:316:38)
    at HandGrammarProgram._requireInVmNodeJsRootParser (C:\pldb\node_modules\scroll-cli\node_modules\jtree\products\GrammarLanguage.js:2026:17)
    at HandGrammarProgram._compileAndReturnRootParser (C:\pldb\node_modules\scroll-cli\node_modules\jtree\products\GrammarLanguage.js:1938:29)
    at HandGrammarProgram.compileAndReturnRootParser (C:\pldb\node_modules\scroll-cli\node_modules\jtree\products\GrammarLanguage.js:2226:67) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\pldb\\node_modules\\scroll-cli\\node_modules\\jtree\\products\\GrammarLanguage.js',
    'C:\\pldb\\node_modules\\scroll-cli\\node_modules\\jtree\\products\\TreeFileSystem.js',
    'C:\\pldb\\node_modules\\scroll-cli\\scroll.js'
  ]
}
node:internal/modules/cjs/loader:1227
  throw err;
  ^

Error: Cannot find module 'C:pldb
ode_modulesscroll-cli
ode_modulesjtreeproducts/Utils.js'
Require stack:
- C:\pldb\node_modules\scroll-cli\node_modules\jtree\products\GrammarLanguage.js
- C:\pldb\node_modules\scroll-cli\node_modules\jtree\products\TreeFileSystem.js
- C:\pldb\node_modules\scroll-cli\scroll.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1224:15)
    at Module._load (node:internal/modules/cjs/loader:1050:27)
    at Module.require (node:internal/modules/cjs/loader:1310:19)
    at require (node:internal/modules/helpers:179:18)
    at evalmachine.<anonymous>:2:19
    at Script.runInThisContext (node:vm:136:12)
    at Object.runInThisContext (node:vm:316:38)
    at HandGrammarProgram._requireInVmNodeJsRootParser (C:\pldb\node_modules\scroll-cli\node_modules\jtree\products\GrammarLanguage.js:2026:17)
    at HandGrammarProgram._compileAndReturnRootParser (C:\pldb\node_modules\scroll-cli\node_modules\jtree\products\GrammarLanguage.js:1938:29)
    at HandGrammarProgram.compileAndReturnRootParser (C:\pldb\node_modules\scroll-cli\node_modules\jtree\products\GrammarLanguage.js:2226:67) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\pldb\\node_modules\\scroll-cli\\node_modules\\jtree\\products\\GrammarLanguage.js',
    'C:\\pldb\\node_modules\\scroll-cli\\node_modules\\jtree\\products\\TreeFileSystem.js',
    'C:\\pldb\\node_modules\\scroll-cli\\scroll.js'
  ]
}
Error in compiled grammar code for language "scroll"
node:internal/modules/cjs/loader:1227
  throw err;
  ^

Error: Cannot find module 'C:pldb
ode_modulesscroll-cli
ode_modulesjtreeproducts/Utils.js'
Require stack:
- C:\pldb\node_modules\scroll-cli\node_modules\jtree\products\GrammarLanguage.js
- C:\pldb\node_modules\scroll-cli\node_modules\jtree\products\TreeFileSystem.js
- C:\pldb\node_modules\scroll-cli\scroll.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1224:15)
    at Module._load (node:internal/modules/cjs/loader:1050:27)
    at Module.require (node:internal/modules/cjs/loader:1310:19)
    at require (node:internal/modules/helpers:179:18)
    at evalmachine.<anonymous>:2:19
    at Script.runInThisContext (node:vm:136:12)
    at Object.runInThisContext (node:vm:316:38)
    at HandGrammarProgram._requireInVmNodeJsRootParser (C:\pldb\node_modules\scroll-cli\node_modules\jtree\products\GrammarLanguage.js:2026:17)
    at HandGrammarProgram._compileAndReturnRootParser (C:\pldb\node_modules\scroll-cli\node_modules\jtree\products\GrammarLanguage.js:1938:29)
    at HandGrammarProgram.compileAndReturnRootParser (C:\pldb\node_modules\scroll-cli\node_modules\jtree\products\GrammarLanguage.js:2226:67) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\pldb\\node_modules\\scroll-cli\\node_modules\\jtree\\products\\GrammarLanguage.js',
    'C:\\pldb\\node_modules\\scroll-cli\\node_modules\\jtree\\products\\TreeFileSystem.js',
    'C:\\pldb\\node_modules\\scroll-cli\\scroll.js'
  ]
}
node:internal/modules/cjs/loader:1227
  throw err;
  ^

Error: Cannot find module 'C:pldb
ode_modulesscroll-cli
ode_modulesjtreeproducts/Utils.js'
Require stack:
- C:\pldb\node_modules\scroll-cli\node_modules\jtree\products\GrammarLanguage.js
- C:\pldb\node_modules\scroll-cli\node_modules\jtree\products\TreeFileSystem.js
- C:\pldb\node_modules\scroll-cli\scroll.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1224:15)
    at Module._load (node:internal/modules/cjs/loader:1050:27)
    at Module.require (node:internal/modules/cjs/loader:1310:19)
    at require (node:internal/modules/helpers:179:18)
    at evalmachine.<anonymous>:2:19
    at Script.runInThisContext (node:vm:136:12)
    at Object.runInThisContext (node:vm:316:38)
    at HandGrammarProgram._requireInVmNodeJsRootParser (C:\pldb\node_modules\scroll-cli\node_modules\jtree\products\GrammarLanguage.js:2026:17)
    at HandGrammarProgram._compileAndReturnRootParser (C:\pldb\node_modules\scroll-cli\node_modules\jtree\products\GrammarLanguage.js:1938:29)
    at HandGrammarProgram.compileAndReturnRootParser (C:\pldb\node_modules\scroll-cli\node_modules\jtree\products\GrammarLanguage.js:2226:67) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\pldb\\node_modules\\scroll-cli\\node_modules\\jtree\\products\\GrammarLanguage.js',
    'C:\\pldb\\node_modules\\scroll-cli\\node_modules\\jtree\\products\\TreeFileSystem.js',
    'C:\\pldb\\node_modules\\scroll-cli\\scroll.js'
  ]
}
C:\pldb\node_modules\scroll-cli\scroll.js:229
    this.scrollProgram = new parser(afterVariablePass)
                         ^

TypeError: parser is not a constructor
    at new ScrollFile (C:\pldb\node_modules\scroll-cli\scroll.js:229:26)
    at ScrollFileSystem._getParsedFile (C:\pldb\node_modules\scroll-cli\scroll.js:66:38)
    at ScrollFileSystem.getScrollFile (C:\pldb\node_modules\scroll-cli\scroll.js:60:17)
    at C:\pldb\node_modules\scroll-cli\scroll.js:76:29
    at Array.map (<anonymous>)
    at ScrollFileSystem.getScrollFilesInFolder (C:\pldb\node_modules\scroll-cli\scroll.js:76:8)
    at ScrollCli.getErrorsInFolder (C:\pldb\node_modules\scroll-cli\scroll.js:752:16)
    at ScrollCli.testCommand (C:\pldb\node_modules\scroll-cli\scroll.js:770:50)
    at ScrollCli.executeUsersInstructionsFromShell (C:\pldb\node_modules\scroll-cli\scroll.js:634:116)
    at Object.<anonymous> (C:\pldb\node_modules\scroll-cli\scroll.js:929:47)

Node.js v22.1.0
~~~
</p>
</details>

The initial problem occurs at:

*"Error: Cannot find module 'C:pldb"*

It would appear that `scroll list | scroll test` does not like the Windows path `c:\pldb` as it has removed the backslash from the path.

Might this be like the typical Linux issue with Windows paths where the backslash has to be escaped with two backslashes (\\\\) to be recognised correctly?

Kind Regards,
Liam

**Comment by breck7** [comment]
Thanks so much @celtic-coder !

https://github.com/breck7/jtree/issues/174

Maybe if we can get jtree working on Windows, it will fix both Scroll and PLDB on windows.
